name: Release Electron UI
on:
  workflow_dispatch:

jobs:
  electron-package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Prepare environment
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_AUTOMATION_TOKEN }}"
          npm install --force rimraf
          yarn global add ts-node typescript
          yarn setup "${{ secrets.NPM_AUTOMATION_TOKEN }}"
          yarn install
          git config --global user.email "bitvalser@gmail.com"
          git config --global user.name "bitvalser"
      - name: Bump version
        run: npx lerna@5.6.2 run release --scope=@bitvalser/animegen-ui
      - name: Download ffmpeg binary
        run: curl -L ${{ secrets.FFMPEG_BIN_URL }} > apps/animegen-ui/assets/libs/ffmpeg.exe
      - name: Build Electron
        run: npx lerna@5.6.2 exec "yarn package" --scope=@bitvalser/animegen-ui
      - name: Release Electron
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.tag }}
          artifacts: "apps/animegen-ui/release/build/*.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
