name: Publish to NPM
on:
  workflow_run:
    workflows: ["Publish to NPM"]
    types:
      - completed

jobs:
  executable-release:
    needs: npm-publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)
      - run: yarn install --ignore-engines
      - run: yarn run compile
      - name: Release  
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.tag }}
          artifacts: "animegen.exe,lib/**/*.js"
          token: ${{ secrets.GITHUB_TOKEN }}   
