name: Release exe for Windows 
on:
  push:
    branches:    
      - main
    tags:
      - v*

jobs:
  executable-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
      - run: yarn install --ignore-engines
      - run: yarn run compile
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "animegen.exe,lib/**/*.js"
          token: ${{ secrets.GITHUB_TOKEN }}      
