name: Release Windows exe
on:
  workflow_run:
    workflows: ["Publish to NPM"]
    types:
      - completed

jobs:
  executable-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0      
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)
      - run: yarn install --ignore-engines
      - run: yarn add --arch=x64 --platform=windows --sharp-install-force sharp --ignore-engines
      - run: yarn run compile
      - run: yarn run archive
      - name: Release  
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.tag }}
          artifacts: "animegen-x64.zip"
          token: ${{ secrets.GITHUB_TOKEN }}   
