name: Publish to NPM
on:
  workflow_dispatch:
  push:
    branches:
      - main
    path:
      - "apps/animegen-lib/**"

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Prepare environment
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_AUTOMATION_TOKEN }}"
          yarn setup "${{ secrets.NPM_AUTOMATION_TOKEN }}"
          yarn install
          git config --global user.email "bitvalser@gmail.com"
          git config --global user.name "bitvalser"
      - name: Release lib
        run: npx lerna run release --scope=@bitvalser/animegen
