name: Publish to NPM
on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_AUTOMATION_TOKEN }}"
      - run: yarn install
      - run: yarn run build:npm
      - run: git config --global user.email "bitvalser@gmail.com"
      - run: git config --global user.name "bitvalser"
      - run: yarn run release 