name: Publish to NPM
on:
  workflow_dispatch:
  push:
    branches:
      - main
    path:
      - "apps/animegen-lib/**"

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_AUTOMATION_TOKEN }}"
      - run: yarn setup "${{ secrets.NPM_AUTOMATION_TOKEN }}"
      - run: yarn install
      - run: git config --global user.email "bitvalser@gmail.com"
      - run: git config --global user.name "bitvalser"
      - run: yarn run release
